import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Nav from "../app/components/nav";
import Footer from "../app/components/footer";
import "./globals.css";

const manrope = Manrope({ 
  subsets: ['latin'],
  weight: ['200','300','400','500','600', '700', '800'], // Add weights you need
  variable: '--font-manrope', // Optional: Define a custom CSS variable
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       
      </head>
      <body className={manrope.className}>
      <Nav />
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
